### ISSUE TITLE
No release and dune-release tarball for the two most recent tags

### ISSUE THREAD

**Issue by Zimmi48** [ocaml-doc/doc-ock-html#11]
Is it an oversight?

**Comment by aantron** [comment]
No, we were using the tarballs generated by GitHub for those releases.

Note, however, that doc-ock-html has been integrated into the main odoc repo at https://github.com/ocaml/odoc, and is not maintained anymore as a separate library.

**Comment by Zimmi48** [comment]
OK, thanks for the answer.

> Note, however, that doc-ock-html has been integrated into the main odoc repo at https://github.com/ocaml/odoc, and is not maintained anymore as a separate library.

I suggest you add a note to the README and GitHub repo description. Then you can use the "archive" feature of GitHub to make the repo read-only.

**Comment by aantron** [comment]
I added a note to the README and "(DEPRECATED)" to the description. We don't want to archive the repo yet, because there may be some branches written against it, and we may want to use the repo to collaborate on porting them.

Going on to do this to the other repos that were merged into ocaml/odoc.

**Comment by dbuenzli** [comment]
~~@aantron maybe you could archive the whole repos no ?~~

Sorry read a little bit to fast...
